### ISSUE TITLE
Planarity of the algorithm 

### ISSUE THREAD

**Issue by ChristopherBlackman** [tinyplasticgreyknight/random-planar-graph#1]
Hi,

I don't know if this is still being maintained, but I found a generated embedding where the graph was not planar. 

Bash : 
python2 GenerateGraph.py --width=5000 --height=5000 --nodes=100 --seed=42 test2.dot
neato -Tpdf test2.dot > test2.pdf

Below is the generated graph : 

![image](https://user-images.githubusercontent.com/7817058/100534935-4b433e00-31e2-11eb-90e5-fc94c06ede62.png)

**Comment by tinyplasticgreyknight** [comment]
It is not maintained.

I checked the specified seed and the graph is indeed planar.  `neato` has chosen a nonplanar _embedding_ of the graph, but that's a different story and graphviz does not guarantee planar embeddings (I gather it's a difficult problem).

This was mentioned in the readme.  As described there, you can add `-n1` to your `neato` invocation to use the default coordinates generated by the python script, which will be a planar embedding.  However, the resulting diagram will probably be "differently ugly".
